### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by bmwilly** [314eter/atom-ocaml-merlin#14]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [ocaml-merlin](https://github.com/314eter/atom-ocaml-merlin) package, v0.8.1
### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /Users/brandon/.atom/packages/ocaml-merlin/lib/main.coffee:154

TypeError: Cannot read property 'file' of undefined
    at Object.module.exports.returnFromDeclaration (/Users/brandon/.atom/packages/ocaml-merlin/lib/main.coffee:154:20)
    at atom-text-editor.subscriptions.add.atom.commands.add.ocaml-merlin:return-from-declaration (/Users/brandon/.atom/packages/ocaml-merlin/lib/main.coffee:47:51)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.6.1/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  3x -5:20.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:19.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -5:19.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:19 core:move-down (atom-text-editor.editor.is-focused)
     -4:40 core:backspace (atom-text-editor.editor.is-focused)
     -4:27.5.0 core:save (atom-text-editor.editor.is-focused)
  7x -2:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:13.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:49.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:47.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:45.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:36.4.0 ocaml-merlin:show-type (atom-text-editor.editor.is-focused)
  2x -0:11.2.0 ocaml-merlin:go-to-declaration (atom-text-editor.editor.is-focused)
     -0:06.3.0 ocaml-merlin:show-type (atom-text-editor.editor.is-focused)
     -0:05.1.0 ocaml-merlin:go-to-declaration (atom-text-editor.editor.is-focused)
  3x -0:03.8.0 ocaml-merlin:return-from-declaration (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "language-gfm",
      "tree-view-autoresize"
    ],
    "excludeVcsIgnoredPaths": false,
    "openEmptyEditorOnStart": false
  },
  "ocaml-merlin": {
    "default": {}
  }
}
```
### Installed Packages

``` coffee
# User
hyperclick, v0.0.36
language-ini, v1.16.0
language-markdown, v0.13.0
language-ocaml, v1.1.2
language-proto, v0.7.0
language-r, v0.4.1
linter, v1.11.4
minimap, v4.24.2
ocaml-indent, v0.3.2
ocaml-merlin, v0.8.1
python-indent, v0.4.3
python-tools, v0.6.7
tabs-to-spaces, v1.0.2
tree-view-big-files, v0.2.2

# Dev
No dev packages
```

**Comment by bmwilly** [comment]
thanks for your work on this and your consistently quick fixes 👍
