### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by stevejb71** [314eter/atom-ocaml-merlin#20]
[Enter steps to reproduce below:]
1. ...Added my opam libs folder to the Merlin path.

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [ocaml-merlin](https://github.com/314eter/atom-ocaml-merlin) package, v0.9.4
### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:298

Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:374:9)
    at Merlin.module.exports.Merlin.restart (/home/steve/.atom/packages/ocaml-merlin/lib/merlin.coffee:20:16)
    at Object.module.exports.restartMerlin (/home/steve/.atom/packages/ocaml-merlin/lib/main.coffee:68:13)
    at /home/steve/.atom/packages/ocaml-merlin/lib/main.coffee:36:8
    at /usr/share/atom/resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:196:28)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-panel.js:254:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1378:25
```
### Commands

```
     -0:00.8.0 core:cut (atom-text-editor#ocaml-merlin.merlinPath.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  },
  "ocaml-merlin": {
    "completePartialPrefixes": true,
    "default": {},
    "merlinPath": "/home/steve/.opam/4.02.3/lib"
  }
}
```
### Installed Packages

``` coffee
# User
coffee-compile, v0.21.1
git-diff-details, v1.3.0
haskell-pointfree, v0.1.3
language-haskell, v1.7.17
language-idris, v0.4.5
language-matlab-octave, v0.1.1
language-ocaml, v1.1.2
language-purescript, v0.7.0
linter, v1.11.14
linter-hlint, v0.4.3
linter-ocaml, v1.2.0
merge-conflicts, v1.4.4
minimap, v4.24.6
ocaml-indent, v0.4.0
ocaml-merlin, v0.9.4

# Dev
No dev packages
```

**Comment by 314eter** [comment]
merlinPath should be the full path to the `ocamlmerlin` executable. In your case, that's probably `/home/steve/.opam/4.02.3/lib/bin/ocamlmerlin`. But if you configured `opam` the recommended way, you can leave it empty.

**Comment by stevejb71** [comment]
Thanks for getting back, after emptying the merlinPath it works fine.
