### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isChanged' of undefined

### ISSUE THREAD

**Issue by captDaylight** [314eter/atom-ocaml-merlin#45]
Whenever I start typing this error is thrown. 

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.4
**Thrown From**: [ocaml-merlin](https://github.com/314eter/atom-ocaml-merlin) package 0.14.4

### Stack Trace

Uncaught TypeError: Cannot read property 'isChanged' of undefined

```
At /Users/paulchristophe/.atom/packages/ocaml-merlin/lib/merlin.coffee:69

TypeError: Cannot read property 'isChanged' of undefined
    at Merlin.module.exports.Merlin.sync (/packages/ocaml-merlin/lib/merlin.coffee:69:47)
    at Merlin.module.exports.Merlin.complete (/packages/ocaml-merlin/lib/merlin.coffee:120:6)
    at Object.getSuggestions (/packages/ocaml-merlin/lib/main.coffee:245:27)
    at providers.forEach.provider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:262:21)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:23)
```

### Commands

```
     -0:52.2.0 core:move-left (input.hidden-input)
     -0:52 editor:newline (input.hidden-input)
     -0:51.7.0 core:move-up (input.hidden-input)
     -0:51.2.0 editor:newline (input.hidden-input)
     -0:49.5.0 core:backspace (input.hidden-input)
     -0:49.1.0 core:move-up (input.hidden-input)
     -0:45 editor:newline (input.hidden-input)
  3x -0:40.8.0 core:backspace (input.hidden-input)
     -0:37.6.0 editor:newline (input.hidden-input)
     -0:32.4.0 core:backspace (input.hidden-input)
     -0:28.9.0 core:move-down (input.hidden-input)
  2x -0:28.5.0 editor:newline (input.hidden-input)
     -0:27.8.0 core:backspace (input.hidden-input)
     -0:21.4.0 editor:newline (input.hidden-input)
  2x -0:18.2.0 core:backspace (input.hidden-input)
  2x -0:13.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-wrap-in-tag 0.6.0 
busy-signal 1.4.3 
editorconfig 2.2.2 
intentions 1.1.5 
language-ethereum 0.3.9 
language-graphql 0.9.0 
language-ini 1.19.0 
language-reason 0.0.4 
linter 2.2.0 
linter-eslint 8.4.0 
linter-flow 5.6.1 
linter-python-pep8 0.2.0 
linter-refmt 0.3.1 
linter-solidity 0.5.0 
linter-ui-default 1.6.10 
multi-cursor-plus 1.2.0 
nuclide 0.264.0 
ocaml-merlin 0.14.4 
react 0.16.3 
reason-refmt 0.3.3 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by sorawee** [comment]
I got this problem too when start typing into an OCaml REPL panel created by https://github.com/rndAdn/REPL-Nodejs.
