### ISSUE TITLE
Error in linter provider OCaml Merlin: This socket is closed

### ISSUE THREAD

**Issue by GGomez99** [314eter/atom-ocaml-merlin#48]
I installed merlin and all the needed packages on atom but when I start using it I get this :
```
C:\Users\guyll\.atom\packages\ocaml-merlin\lib\merlin.coffee:43 Merlin process started, pid = 12708
C:\Users\guyll\.atom\packages\ocaml-merlin\lib\merlin.coffee:41 Merlin exited with code 0
C:\Users\guyll\.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:52 [2018-02-07T20:28:47.169Z] [ERROR] atom-ide-diagnostics - Error in linter provider OCaml Merlin: This socket is closed
Error: This socket is closed
    at Socket._writeGeneric (net.js:683:19)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at Interface._writeToOutput (readline.js:256:17)
    at Interface.prompt (readline.js:221:10)
    at Interface.question (readline.js:234:12)
    at file:///C:/Users/guyll/.atom/packages/ocaml-merlin/lib/merlin.coffee:42:20
    at file:///C:/Users/guyll/.atom/packages/ocaml-merlin/lib/merlin.coffee:40:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
C:\Users\guyll\.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:52 [2018-02-07T20:28:47.222Z] [ERROR] installErrorReporter - Caught unhandled rejection This socket is closed
Error: This socket is closed
    at Socket._writeGeneric (net.js:683:19)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at Interface._writeToOutput (readline.js:256:17)
    at Interface.prompt (readline.js:221:10)
    at Interface.question (readline.js:234:12)
    at file:///C:/Users/guyll/.atom/packages/ocaml-merlin/lib/merlin.coffee:42:20
    at file:///C:/Users/guyll/.atom/packages/ocaml-merlin/lib/merlin.coffee:40:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
It looks like merlin is not run correctly even tho I added the path to ocamlmerlin.exe in the configs of atom-ocaml-merlin and ocaml nuclide...
I use Ocaml 4.06.0 and Merlin 3.0.5, installed with Cygwin on Windows 10.

**Comment by GGomez99** [comment]
I found the origin of the problem : Merlin >=3.0 is not compatible with Cygwin. Here is the issue on the Merlin git : 
https://github.com/ocaml/merlin/issues/754
This incompatibility is still not solved, so I had to downgrade Merlin and Ocaml, and now everything works fine.
