### ISSUE TITLE
Failed to activate the ocaml-merlin package

### ISSUE THREAD

**Issue by evanpjensen** [314eter/atom-ocaml-merlin#50]
When opening an Ocaml file with the latest atom an error prevents ocaml-merlin from loading. 

Atom 1.32.0
Ubuntu 18.04.1 LTS

```
Community Packages (33) /home/wont/.atom/packages
├── advanced-open-file@0.16.8
├── autocomplete-python@1.10.12
├── build@0.70.0
├── build-make@0.13.0
├── busy-signal@1.4.3
├── file-icons@2.1.25
├── highlight-selected@0.14.0
├── intentions@1.1.5
├── language-babel@2.85.0
├── language-graphql@0.11.0
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-solidity@0.1.1
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0
├── linter-ocaml@1.2.0
├── linter-ui-default@1.7.1
├── minimap@4.29.9
├── minimap-linter@2.2.0
├── nuclide-format-js@0.0.47
├── ocaml-indent@0.7.0
├── ocaml-merlin@0.14.5
├── pdf-view@0.71.0
├── script@3.18.1
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.10
```

# Error
Cannot call a class as a function

# Stacktrace
```
TypeError: Cannot call a class as a function
    at _classCallCheck (/usr/share/atom/resources/app/static/<embedded>:11:1187348)
    at Disposable (/usr/share/atom/resources/app/static/<embedded>:11:1187399)
    at Object.consumeIndent (/home/wont/.atom/packages/ocaml-merlin/lib/main.coffee:285:5)
    at Provider.t.exports.Provider.provide (/usr/share/atom/resources/app/static/<embedded>:14:1032575)
    at ServiceHub.t.exports.ServiceHub.consume (/usr/share/atom/resources/app/static/<embedded>:11:2897068)
    at Package.activateServices (/usr/share/atom/resources/app/static/<embedded>:11:2905200)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:2902034)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/usr/share/atom/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1184658)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1186099)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (/usr/share/atom/resources/app/static/<embedded>:11:378761)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:378723)
    at /usr/share/atom/resources/app/static/<embedded>:11:911619
    at r (/usr/share/atom/resources/app/static/<embedded>:11:906225)
    at o (/usr/share/atom/resources/app/static/<embedded>:14:1035482)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1035636)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1034238)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by goldenHairDafo** [comment]
Same Error on Arch Linux, but diffrent StackTrace:

[Enter steps to reproduce:]

1. Start Atom
2. Open a .ml file

**Atom**: 1.32.0 x64
**Electron**: 2.0.12
**OS**: linux 4.18.14-arch1-1-ARCH
**Thrown From**: [ocaml-merlin](https://github.com/atom-ocaml/ocaml-merlin) package 0.14.6


### Stack Trace

Failed to activate the ocaml-merlin package

```
At Cannot call a class as a function

TypeError: Cannot call a class as a function
    at _classCallCheck (/usr/lib/atom/node_modules/event-kit/dist/disposable.js:3:99)
    at Disposable (/usr/lib/atom/node_modules/event-kit/dist/disposable.js:36:5)
    at Object.consumeIndent (/packages/ocaml-merlin/lib/main.coffee:285:5)
    at Provider.module.exports.Provider.provide (/usr/lib/atom/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.consume (/usr/lib/atom/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.activateServices (/usr/lib/atom/src/package.js:399:73)
    at Package.activateNow (/usr/lib/atom/src/package.js:227:14)
    at activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/usr/lib/atom/src/package.js:895:75)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at PackageManager.triggerDeferredActivationHooks (/usr/lib/atom/src/package-manager.js:724:34)
    at Promise.all.then (/usr/lib/atom/src/package-manager.js:657:12)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-debugger-native-gdb 0.7.3 
atom-ide-debugger-ocaml 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
busy-signal 1.4.3 
intentions 1.1.5 
language-ocaml 1.9.5 
linter 2.2.0 
linter-ocaml 1.2.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-linter 2.2.1 
ocaml-indent 0.7.1 
ocaml-merlin 0.14.6 
vim-mode-plus 1.35.0 
```
Hope this gives some more insides. Thanks for the work!
